### ISSUE TITLE
Build OpenAPI Specification Swagger file(s)

### ISSUE THREAD

**Issue by meteabduraman** [plesanueduard/webtechdevproject#1]
Have a **Swagger file** for the API/one for each of the APIs. A Swagger file helps clients that want to use your API to know how to communicate with it and what to expect as responses (it discloses information about the available endpoints, request bodies, response status codes, etc.)

❗️This is needed for the **2nd phase of the Project**, due **December 5th, 2024**❗️
❗️Checkout more details about the assignment on [online.ase.ro](https://online.ase.ro)❗️

Checkout [this example](https://editor-next.swagger.io/).

Additional links:
- [OpenAPI standard definition](https://swagger.io/specification/)
- [express-openapi](https://www.npmjs.com/package/express-openapi) npm library for automatic creation of Swagger files
- [Swagger Online Editor](https://editor-next.swagger.io/) helping to manually build the Swagger file

This file (or .zip archive of files) then should be uploaded on [online.ase.ro](https://online.ase.ro).

**Comment by meteabduraman** [comment]
@plesanueduard can you link your Github Project to this repository? Seems like I cannot mark this issue as part of your Github project 🤔

**Comment by plesanueduard** [comment]
@meteabduraman is it okay now?

**Comment by meteabduraman** [comment]
@plesanueduard awesome thanks
